services:
  email:
    image: mailhog/mailhog
    platform: linux/amd64 # for Apple Silicon macs
    ports:
      - "127.0.0.1:1025:1025" # SMTP (Jenkins on host has access to SMTP port 1025 via localhost)
      - "127.0.0.1:8025:8025" # web UI (you use this to monitor test emails)
    restart: unless-stopped
